package com.ppamy.pptips.dbs.tips_dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ppamy.pptips.dbs.tips_dao.Tips;

import com.ppamy.pptips.dbs.tips_dao.TipsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tipsDaoConfig;

    private final TipsDao tipsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tipsDaoConfig = daoConfigMap.get(TipsDao.class).clone();
        tipsDaoConfig.initIdentityScope(type);

        tipsDao = new TipsDao(tipsDaoConfig, this);

        registerDao(Tips.class, tipsDao);
    }
    
    public void clear() {
        tipsDaoConfig.getIdentityScope().clear();
    }

    public TipsDao getTipsDao() {
        return tipsDao;
    }

}
