package com.ppamy.pptips.dbs.tips_dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TIPS.
 */
public class Tips {

    private Long id;
    private Long date;
    private Long action_date;
    private String longitude;
    private String latitude;
    private String loc_name;
    private String subject;
    private String body;
    private Integer type;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Tips() {
    }

    public Tips(Long id) {
        this.id = id;
    }

    public Tips(Long id, Long date, Long action_date, String longitude, String latitude, String loc_name, String subject, String body, Integer type) {
        this.id = id;
        this.date = date;
        this.action_date = action_date;
        this.longitude = longitude;
        this.latitude = latitude;
        this.loc_name = loc_name;
        this.subject = subject;
        this.body = body;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }

    public Long getAction_date() {
        return action_date;
    }

    public void setAction_date(Long action_date) {
        this.action_date = action_date;
    }

    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getLoc_name() {
        return loc_name;
    }

    public void setLoc_name(String loc_name) {
        this.loc_name = loc_name;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
